In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [50]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print('numpy:{:.6f}'.format((toc - tic) * 1000))

tic = time.time()
c = [ai * bi for ai, bi in zip(a, b)]
toc = time.time()
print('[]:{:.6f}'.format((toc - tic) * 1000))

tic = time.time()
c = []
for ai, bi in zip(a, b):
    c.append(ai * bi)
toc = time.time()
print('loop:{:.6f}'.format((toc - tic) * 1000))

numpy:12.752056
[]:189.430952
loop:336.066961


In [55]:
A = np.eye(3)
v = np.ones(3)
print(A, v, np.dot(A, v)) # we eliminated 2 loops here

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]] [ 1.  1.  1.] [ 1.  1.  1.]


In [59]:
np.exp(v), np.log(v), 1 / v

(array([ 2.71828183,  2.71828183,  2.71828183]),
 array([ 0.,  0.,  0.]),
 array([ 1.,  1.,  1.]))

### broadcasting

In [68]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [69]:
cal = A.sum(axis=0)
print(A.sum(), cal.sum(), A.sum(axis=0), A.sum(axis=1))

530.3 530.3 [  59.   239.   155.4   76.9] [ 128.4  165.2  236.7]


In [70]:
cal.reshape(1,4)

array([[  59. ,  239. ,  155.4,   76.9]])

In [72]:
percentage = A / cal.reshape(1,4)
print(percentage)

[[ 0.94915254  0.          0.02831403  0.88426528]
 [ 0.02033898  0.43514644  0.33462033  0.10403121]
 [ 0.03050847  0.56485356  0.63706564  0.01170351]]


In [73]:
np.array([1, 2, 3, 4]) + 100

array([101, 102, 103, 104])

In [76]:
A = np.array([[1, 2, 3], 
          [4, 5, 6]])
b = np.array([100, 200, 300])
print(A, b, A + b)

[[1 2 3]
 [4 5 6]] [100 200 300] [[101 202 303]
 [104 205 306]]


In [90]:
c = np.array([[100], [200]])
print(A + c, A.shape, c.shape)

[[101 102 103]
 [204 205 206]] (2, 3) (2, 1)


### don't use 'rank 1' arrays

In [91]:
a = np.random.randn(5)
print(a.shape, a, a.T, np.dot(a, a.T))

(5,) [-0.04592636 -0.96750623 -0.76178034  0.73884134  1.6061133 ] [-0.04592636 -0.96750623 -0.76178034  0.73884134  1.6061133 ] 4.64397330055


In [93]:
a = np.random.randn(5, 1) # column vector
print(a.shape)
print(a)
print(a.T) # row vector
print(np.dot(a, a.T))

(5, 1)
[[ 0.78697789]
 [-1.49533458]
 [-0.46836999]
 [-0.44529441]
 [-0.19537864]]
[[ 0.78697789 -1.49533458 -0.46836999 -0.44529441 -0.19537864]]
[[ 0.6193342  -1.17679525 -0.36859682 -0.35043686 -0.15375867]
 [-1.17679525  2.23602549  0.70036983  0.66586413  0.29215644]
 [-0.36859682  0.70036983  0.21937044  0.20856254  0.09150949]
 [-0.35043686  0.66586413  0.20856254  0.19828711  0.08700102]
 [-0.15375867  0.29215644  0.09150949  0.08700102  0.03817281]]
